SELECT
    CASE
        WHEN BIRTHDAY = (SELECT MAX(BIRTHDAY) FROM worker) THEN 'YOUNGEST'
        WHEN BIRTHDAY = (SELECT MIN(BIRTHDAY) FROM worker) THEN 'OLDEST'
    END AS type,
    NAME AS name,
    BIRTHDAY AS birthday
FROM
    worker
WHERE
    BIRTHDAY = (SELECT MIN(BIRTHDAY) FROM worker)
OR
    BIRTHDAY = (SELECT MAX(BIRTHDAY) FROM worker);
